name: Build and Deploy

on:
  push:
    branches:
      - main
      # - release

jobs:
  FTP-Deploy:
    name: FTP Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Deploy to STAGING
        if: github.ref == 'refs/heads/main'
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER_STAGING }}
          username: ${{ secrets.FTP_USERNAME_STAGING }}
          password: ${{ secrets.FTP_PASSWORD_STAGING }}
          local-dir: ./
          server-dir: /
          
      # - name: Deploy to Release
      #   if: github.ref == 'refs/heads/release'
      #   uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      #   with:
      #     server: ${{ secrets.FTP_SERVER }}
      #     username: ${{ secrets.FTP_USERNAME }}
      #     password: ${{ secrets.FTP_PASSWORD }}
      #     local-dir: ./
      #     server-dir: ~/public_html/if-tech.co.jp/wp-content/themes/ifBrandSite/